# SPDX-FileCopyrightText: 2026 GARDENA GmbH
# SPDX-FileCopyrightText: 2026 Reto Schneider
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build project

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read

jobs:

  component_tests:
    name: Component Tests
    runs-on: ubuntu-26.04
    steps:
      - name: Install system dependencies
        run: |
          sudo apt update \
          && sudo apt install --yes --no-install-recommends \
            bubblewrap \
            inotify-tools
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.14
          update-environment: true
      - uses: abatilo/actions-poetry@3765cf608f2d4a72178a9fc5b918668e542b89b1 # v4.0.0
        with:
          poetry-version: 2.5.1
      - name: Install component tests
        run: poetry install
        working-directory: ./tests
      - name: Prepare component-test networking (workaround for bublewrap)
        run: |
          sudo install -d -m 755 /run/netns
          sudo chmod 755 /run/netns

